replicaCount: 2

image:
  repository: "" 
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

configMap:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"